subprojects {
    plugins.withId("com.android.base") {
        android {
            compileSdk = 37
            ndkVersion = "29.0.13113456"
            
            defaultConfig {
                minSdk = 24
                targetSdk = 37
            }
            
            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_21
                targetCompatibility = JavaVersion.VERSION_21
            }
        }
    }
}

apply from: 'api/manifest.gradle'

ext {
    versionCode = 101000
    versionName = "1.1"
}
